### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by kvdesa** [okmr-d/DOFavoriteButton#14]
I'm wondering, are you going to port this to Swift 2.0?

**Comment by palcalde** [comment]
+1

**Comment by palcalde** [comment]
I just did it. Check #15.

**Comment by sicaboy** [comment]
+1

**Comment by chayelheinsen** [comment]
You should update the pod then @okmr-d

**Comment by grantkemp** [comment]
+1 for me too

**Comment by alexruperez** [comment]
:+1:

**Comment by grantkemp** [comment]
Guys - we have been waiting for update for ages and it seems that its not being maintained. how do we contact the author to request if we can fork it?
