### ISSUE TITLE
Please update the version in cocoapods

### ISSUE THREAD

**Issue by kaphacius** [okmr-d/DOFavoriteButton#17]
Does not compile in latest Xcode

**Comment by grantkemp** [comment]
+1

**Comment by sinanulkuatam** [comment]
+1 @okmr-d pls update the podfile

**Comment by tbaranes** [comment]
+1

**Comment by grantkemp** [comment]
How do we use this without Cocoapods? 

Can we fork and push it up ourselves if the owner doesn't want to maintain this on Cocoapods?

@okmr-d  would be great if you can update on Cocoapods !

**Comment by tbaranes** [comment]
The master is working (just some warnings for swift 2.2), so you can use this library with Cocoapods adding this line in your Podfile:

```
    pod 'DOFavoriteButton', :git => 'https://github.com/okmr-d/DOFavoriteButton.git'
```
