### ISSUE TITLE
Do you mind if I translate DOFavoriteButton to Objective-C version?

### ISSUE THREAD

**Issue by wtuyp** [okmr-d/DOFavoriteButton#18]
I'm not good at reading Swift language, 
do you mind if I translate DOFavoriteButton to Objective-C?
Thanks!

**Comment by trdavidson** [comment]
hey @wtuyp - did you ever come around writing the objective-c implementation? I've been trying for some time now without much luck... :/

**Comment by kmiloaguilar** [comment]
@wtuyp did you translated to obj-c?
