### ISSUE TITLE
IB Designables errors via storyboard

### ISSUE THREAD

**Issue by famAlex** [okmr-d/DOFavoriteButton#4]
Hi, thank you for sharing this nice animation button, i really like it!

I manually installed the library and followed the instructions for storyboard setup and it works but it also gives me two red errors that I'm going to report:

1)  IB Designables: Failed to update auto layout status: Interface Builder Cocoa Touch Tool crashed;
2) IB Designables: Failed to render instance of DOFavoriteButton: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance.

Am I making any mistakes?

Kind regards
Alessandro

**Comment by okmr-d** [comment]
Thank you for informing me.
I fixed this issue.
Please check.

**Comment by famAlex** [comment]
Thank you for your kind help, I'm really enthusiast about your animation.
After the update, i tried with the manual installation and I wasn't lucky, so I went with pod and at the beginning the same error appeared.
What worked for me was deleting old outlets and make a new ones: from the identity inspector I saw the "module" field auto filled like the image.
I apologize in case i was the reason of error ;-)
<img width="258" alt="schermata 2015-07-21 alle 10 18 50" src="https://cloud.githubusercontent.com/assets/13166743/8796815/ee9f09ce-2f97-11e5-9c1c-40613c13800a.png">

**Comment by okmr-d** [comment]
I'm sorry. I made a mistake.
Please confirm that again.

**Comment by famAlex** [comment]
Hi, 
I made a new project to give you a feedback as the last version you've posted worked as I mentioned.

Starting from an empty view controller, I dragged a button, changed the class, created the outlet and added the action following your instructions.
This time the Module filed remains empty but after the launch, the app crash with these errors:

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Reason: image not found

PS: I used your icons, so I'm quite sure that they are in ;-)
PPS: From my experience, the previous version was perfect and I'm continuing using it so I can just thank you and stay with it
