### ISSUE TITLE
You should credit Twitter iOS App as the source of this idea.

### ISSUE THREAD

**Issue by cabeca** [okmr-d/DOFavoriteButton#7]
This is an awesome Pod, but you should credit Twitter's iOS App as the inspiration for the animation somewhere in the README.

**Comment by palcalde** [comment]
:+1:

**Comment by okmr-d** [comment]
Thank you for pointing it out.
DOFavoriteButton was Inspired by Twitter's iOS App, so credit definitely goes there.
I really like Twitter's iOS App.
