### ISSUE TITLE
Make some Buttons selected by default

### ISSUE THREAD

**Issue by AruLNadhaN** [okmr-d/DOFavoriteButton#9]
Thanks for building this great library. I am using the DoFavourite Button for Bookmarking feature in my App. I want some buttons to be selected by default. By the way i am using tableview to populate my data like this http://i.imgur.com/VoCxkJa.png

**Comment by okmr-d** [comment]
It is the same way as UIButton.
* by coding
```swift
button.selected = true
```

* by StoryBoard  
Attributes Inspector -> Control -> Content  
Check `Selected` checkbox
